// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback configuration for Lovable Cloud
const FALLBACK_SUPABASE_URL = 'https://gyvtgzdkuhypteiyhtaq.supabase.co';
const FALLBACK_SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dnRnemRrdWh5cHRlaXlodGFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MzUyNDksImV4cCI6MjA3NzQxMTI0OX0.5RQlrroKXcEJn7jmkRcMYfi3b2U4dbh3OGqho1psctQ';

// Use environment variables if available, otherwise use fallback
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Export a flag to check if Supabase is configured
export const isSupabaseConfigured = true;